[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@thirdweb-dev/=node_modules/@thirdweb-dev/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Optimizer settings for smaller contract size
optimizer = true
optimizer_runs = 200  # Lower runs = smaller bytecode size (prioritize size over gas efficiency)

# See more config options https://github.com/foundry-rs/foundry/tree/master/config